# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo check
  except:
  - master

pages:
  script:
  - cd exampleSite ; hugo --themesDir ../../ --minify
  artifacts:
    paths:
    - exampleSite/public
  only:
  - master
