image: registry.gitlab.com/pages/hugo:latest

pages:
  script:
  - cd exampleSite ; hugo --themesDir ../../ --minify
  artifacts:
    paths:
    - ./exampleSite/public
  only:
  - master
  
test:
  script:
  - hugo
  except:
  - master